name: the-office-quotes-prod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

  test:
    runs-on: windows-latest
    needs: [build]
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'

    - name: Install dependencies
      run: dotnet restore 
    - name: Test
      run: dotnet test --no-restore --verbosity normal

  deploy:
    runs-on: windows-latest
    needs: [build, test]
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'

    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/the-office-quotes

    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: the-office-quotes
        publish-profile: ${{ secrets.azure_prod_profile }}
        package: ${{env.DOTNET_ROOT}}/the-office-quotes
